import '../../../domain/entities/user_entity.dart';

class UserModel extends UserEntity {
  UserModel({
    required String id,
    required String name,
    required String email,
    required String password,
    required String cpf,
    required String phone,
    required String cellphone,
    required String crmCrp,
    required String gender,
    required String specialty,
    required String street,
    required String number,
    required String neighborhood,
    required String city,
    required String state,
    required double price,
    required String description,
    required String courses,
    required String healthPlan,
    required bool bathroomSpecifc,
    required String linkedin,
  }) : super(
          id: id,
          name: name,
          email: email,
          password: password,
          cpf: cpf,
          phone: phone,
          cellphone: cellphone,
          crmCrp: crmCrp,
          gender: gender,
          specialty: specialty,
          street: street,
          number: number,
          neighborhood: neighborhood,
          city: city,
          state: state,
          price: price,
          description: description,
          courses: courses,
          healthPlan: healthPlan,
          bathroomSpecifc: bathroomSpecifc,
          linkedin: linkedin,
        );

        factory UserModel.fromJson(Map<String, dynamic> json){
    return UserModel(
      id: json['id'],
          name: json['name'],
          email: json['email'],
          password: json['password'],
          cpf: json['cpf'],
          phone: json['phone'],
          cellphone: json['cellphone'],
          crmCrp: json['crmCrp'],
          gender: json['gender'],
          specialty: json['specialty'],
          street: json['street'],
          number: json['number'],
          neighborhood: json['nieghborhood'],
          city: json['city'],
          state: json['state'],
          price: json['price'],
          description: json['description'],
          courses: json['courses'],
          healthPlan: json['heathPlan'],
          bathroomSpecifc: json['bathroomSpecifc'],
          linkedin: json['linkedin'],
    );
  }
}
